services:

  api_bun_mongodb:
    container_name: api-bun-mongodb
    image: lincenying/api-bun-mongodb:${TAG}
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: mongodb://db_mongo:27017
    env_file:
      - .env
    ports:
      - 14080:14080
    depends_on:
      - db_mongo
    networks:
      - webnet

  db_mongo:
    container_name: db-mongo
    image: mongo:7
    volumes:
      - ${MONGODB_DIR:-/data/db}:/data/db
    ports:
      - 27017:27017
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
