services:
  api_bun:
    container_name: api-bun-server
    image: lincenying/bun-api-server:${TAG}
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: mongodb://api_mongo:27017
    env_file:
      - .env
    ports:
      - 4000:4000
    depends_on:
      - api_mongo
    networks:
      - webnet

  api_mongo:
    container_name: api-bun-mongo-server
    image: mongo:7
    volumes:
      - /Users/lincenying/web/mongodb7/data:/data/db
    ports:
      - 27017:27017
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
